---
# tasks file for vpn

- name: All servers | Install EPEL
  yum: epel-release
  state: present

- name: All servers | Install OpenVPN
  yum:
  - openvpn
  - iperf3
  state: present

- name: All servers | Put SELinux in permissive mode, logging actions that would be blocked
  selinux:
    policy: targeted
    state: permissive

- name: Server | Configure OpenVPN server
  block:
  - name: generate server key
    command: openvpn --genkey --secret /etc/openvpn/static.key

  - name: copy server config file
    copy:
      src: server/server.conf
      dest: etc/openvpn/server.conf
    notify: openvpn server restart
  when: ansible_hostname == "server"


