---
# tasks file for vpn

- name: All servers | Install EPEL
  yum: 
    name: epel-release
    state: present

- name: All servers | Install OpenVPN
  yum:
    name:
    - openvpn
    - iperf3
    state: present

- name: All servers | Put SELinux in permissive mode, logging actions that would be blocked
  selinux:
    policy: targeted
    state: permissive

- name: All servers | Configure OpenVPN
  copy:
    src: {{ item }}/{{ item }}.conf
    dest: /etc/openvpn/{{ item }}.conf
  notify: openvpn restart
  when: ansible_hostname == "{{ item }}"
  loop:
  - "server"
  - "client"

- name: Server | generate server key
  command: openvpn --genkey --secret /etc/openvpn/static.key
  when: ansible_hostname == "server"



